### ISSUE TITLE
流程引擎切换至activiti后，创建用户任务报错

### ISSUE THREAD

**Issue by zyf540860996** [majinhui9/bpmn-vue3#1]
流程引擎切换至activiti后，创建用户任务报错

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isGeneric')
    at eie.build (index.ce7ed5e5.js:22:437660)
    at index.ce7ed5e5.js:22:440316
    at Aa (index.ce7ed5e5.js:1:68551)
    at index.ce7ed5e5.js:22:440240
    at Aa (index.ce7ed5e5.js:1:68551)
    at eie.parseContainments (index.ce7ed5e5.js:22:439862)
    at eie.build (index.ce7ed5e5.js:22:438080)
    at index.ce7ed5e5.js:22:440316
    at Aa (index.ce7ed5e5.js:1:68551)
    at index.ce7ed5e5.js:22:440240

请问下怎么解决？

**Comment by zyf540860996** [comment]
需要替换json文件，用这个地址的文件就好了  https://github.com/miyuesc/bpmn-process-designer/blob/v2/packages/moddle-extensions/activiti.json

**Comment by xujipeng19991227** [comment]
> 需要替换json文件，用这个地址的文件就好了 https://github.com/miyuesc/bpmn-process-designer/blob/v2/packages/moddle-extensions/activiti.json

感谢

**Comment by wangShiBoGT** [comment]
> 需要替换json文件，用这个地址的文件就好了 https://github.com/miyuesc/bpmn-process-designer/blob/v2/packages/moddle-extensions/activiti.json

问下怎么切换flowable工作流
